Preprocessors for RPi Pico
OXRS-IO/OXRS-IO-API-ESP32-LIB pull request #26
Opened 2023-08-17 08:25 UTC by mthorley

Updates to support OXRS_API for RPi Pico devices. 
Please refer to https://github.com/mthorley/pico-aqs for further details.

2023-08-17 21:22 UTC, sumnerboy12 requested changes
Looks really good Matt, just a few tweaks in the README etc but code-wise I think it looks fine. Thanks very much for contributing back!

2023-08-17 21:22 UTC, sumnerboy12 commented on library.properties
> +sentence=ESP32 and PicoW API library for Open eXtensible Rack System firmware
I wonder if we just change this to `API library for Open...`?

2023-08-17 21:22 UTC, sumnerboy12 commented on README.md
> +# ESP32 and PicoW API library for [OXRS](https://oxrs.io)
Maybe change this title to `API library for...` and then underneath list the devices it supports?

Then it is easy to add to this list in the README.

Ideally we would rename the repo as well, but I think that can wait.

2023-08-18 06:54 UTC, mthorley commented
Updated to reflect better documentation as suggested.

2023-08-18 07:14 UTC, moinmoin-sh approved these changes
Looks good to me

2023-08-18 08:42 UTC, sumnerboy12 approved these changes

2023-08-18 08:43 UTC, merged